apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: akazwzdotcom-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: akazwz@outlook.com
    privateKeySecretRef:
      name: akazwzdotcom-clusterissuer-private-key
    solvers:
      - http01:
          ingress:
            class: traefik