apiVersion: apps/v1
kind: Deployment
metadata:
  name: akazwzdotcom-deployment
  namespace: akazwzdotcom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: akazwzdotcom
  template:
    metadata:
      labels:
        app: akazwzdotcom
    spec:
      containers:
        - name: akazwzdotcom
          image: akazwz/akazwzdotcom:f587489
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 1024Mi
          env:
            - name: NODE_ENV
              value: production